version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "prime-crawler"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-88uscd0uoxk0"
s3_prefix = "prime-crawler"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
